# Base image
FROM ubuntu:16.04

# Headless install (otherwise it hangs)
ENV DEBIAN_FRONTEND=noninteractive

# System updates
RUN apt-get update && apt -y install software-properties-common nodejs npm 

#postgresql postgresql-contrib (is this needed?)

